### PR TITLE
Process

### PR DESCRIPTION
**Pull request by OpenGlobe**

### CODE REVIEW

**Comment by OpenGlobe** [comment]
@emileighoutlaw any thoughts here?  Does this work?

**Comment by emileighoutlaw** [comment]
Taking a look now!

**Comment by emileighoutlaw** [comment]
I made a change to leave out the "If it looks promising" part, which feels to me super selective and a bit arbitrary. I don't believe NTIS is currently having an issue with having too many inquiries, and if they are I think we could address it better in other sections of the website.

I made a couple other small tweaks to the language. Can you double check point #4 and make sure it's still correct @OpenGlobe ?  I changed the adjective from "notify the team" to "notify your team" for specificity.

**Comment by OpenGlobe** [comment]
That reads a lot better @emileighoutlaw !  I made one, slight adjustment to the approval language.  Does that sound ok?  I think everything else looks pretty good, and I like how it's reading.

**Comment by emileighoutlaw** [comment]
Looks good to me! Merging.

**Pull request merged**
