### PR TITLE
New pages new content

### PR DESCRIPTION
**Pull request by OpenGlobe**
@emileighoutlaw - can you take a look at this content and let me know what you think?  I’m working on fleshing out some of the details a bit further (don’t worry about merging yet or anything, but want to flag the changes for review here)

### CODE REVIEW

**Comment by emileighoutlaw** [comment]
Taking a look now!

**Comment by emileighoutlaw** [comment]
I made some edits — want to do a sanity check @OpenGlobe ? Otherwise, this good to me.

**Comment by OpenGlobe** [comment]
Hey @emileighoutlaw - can you take a look at the edits above?  Because of the uniqueness of the JV authority, we want to make it somehow clear that it's best for projects that don't have good alternatives elsewhere. 

See #5 here as an example - https://www.ntis.gov/assets/pdf/FAQsFull_FINAL_070816.pdf

**Comment by OpenGlobe** [comment]
Ok, great @emileighoutlaw !  Thanks for taking a quick look -

**Pull request merged**
